contabilidade/urls.py
from django.urls import path
from contabilidade.views import IndexView, CreateContaView, UpdateContaView, DeleteContaView

app_name = 'contabilidade'

urlpatterns = [
    path('', IndexView.as_view(), name='homepage'),
    path('novaconta/', CreateContaView.as_view(), name='nova_conta'),
    path('<int:pk>/alterar/', UpdateContaView.as_view(), name='alterar_conta'),
    path('<int:pk>/excluir/', DeleteContaView.as_view(), name='excluir_conta'),
]

projeto_contabil/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('painel/', admin.site.urls),
    path('', include('contabilidade.urls')),
]

contabilidade/models.py
from django.db import models
from django.db.models import signals
from django.template.defaultfilters import slugify

class Base(models.Model):
    criado = models.DateField('Data de Criação', auto_now_add=True)
    modificado = models.DateField('Data de Atualização', auto_now=True)
    ativo = models.BooleanField('Status', default=True)

    class Meta:
        abstract=True

class Conta(Base):
    nome = models.CharField('Conta', max_length=100, error_messages='Dê um nome para a conta')
    descricao = models.TextField('Descrição', max_length=300,)
    saldo = models.DecimalField('Saldo em R$', max_digits=9, decimal_places=2, default=0.00, help_text='Saldo financeiro da conta em Reais(R$)')
    slug = models.SlugField('Slug', max_length=100, blank=True, editable=False)

    def __str__(self):
        return self.nome
    
def conta_pre_save(signal, instance, sender, **kwargs):
    instance.slug = slugify(instance.nome)

signals.pre_save.connect(conta_pre_save, sender=Conta)

contabilidade/forms.py
from django import forms
from .models import Conta

class ContaModelForm(forms.ModelForm):
    ativo = forms.BooleanField(
        label = 'Status',
        help_text='Marcado significa que a conta estará ativa.'
    )
    nome = forms.CharField(
        label = 'Conta',
        required=True,
        min_length= 4,
        max_length=100,
        error_messages={
            'min_length':'O nome de uma conta precisa de no mínimo 4 caracteres',
            'max_length':'O nome da conta não pode ultrapassar 100 caracteres',
        },
        widget=forms.TextInput(
            attrs={'placeholder':'Nome da conta financeira'}
        )
    )
    descricao = forms.CharField(
        label = 'Descrição',
        required = False,
        max_length = 300,
        widget=forms.Textarea(
            attrs={'rows':"3", "cols":"70", "placeholder":"Uma breve descrição"}
        )
    )
    saldo = forms.DecimalField(
        label = 'Saldo em R$',
        required=False,
        max_digits=9,
        decimal_places=2,
        min_value=0,
        error_messages={
            'min_value':'O saldo não pode ser menor que zero',
        }
    )
    
    class Meta:
        model = Conta
        fields = [
            'ativo',
            'nome',
            'descricao',
            'saldo',
        ]

contabilidade/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Conta
from django.urls import reverse_lazy
from .forms import ContaModelForm

class IndexView(ListView):
    models = Conta
    template_name = 'homepage.html'
    queryset = Conta.objects.all().order_by('nome')
    context_object_name = 'contas'

class CreateContaView(CreateView):
    model = Conta
    template_name = 'conta_nova.html'
    form_class = ContaModelForm
    success_url = reverse_lazy('contabilidade:nova_conta')

class UpdateContaView(UpdateView):
    model = Conta
    template_name = 'conta_nova.html'
    fields = [
        'ativo',
        'nome',
        'descricao',
        'saldo'
    ]
    success_url = reverse_lazy('contabilidade:homepage')

class DeleteContaView(DeleteView):
    model = Conta
    template_name = 'conta_del.html'
    success_url = reverse_lazy('contabilidade:homepage')

contabilidade/templates/base.html
{% include 'partials/head.html' %}

<body>
    {% include 'partials/header.html' %}
    {% block conteudo %} {% endblock %}
    {% include 'partials/footer.html' %}
</body>

</html>

contabilidade/templates/conta_del.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

<body>
    {% block conteudo %}
    <main>
        <div class="container-fluid">
            <div id="conta-nova">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <h3 class="main-title">Conta</h3>
                        </div>
                        <!-- Dividindo em duas colunas da mesma largura -->
                        <div class="col-md-6">
                            <img class="img-fluid" src="{% static 'img/agencia.jpg' %}" alt="Fachada de uma empresa">
                        </div>
                        <div class="col-md-6">
                            <h3 class="about-title">Conta Financeira</h3>
                            <form method="POST">
                                {% csrf_token %}
                                <p>Tem certeza que quer excluir a conta {{ object }}</p>
                                {{ buttons }}
                                <button type="submit" class="btn btn-danger">Confirma??</button>
                                <button type="button" class="btn btn-warning">
                                    <a href="{% url 'contabilidade:homepage' %}">Cancelar</a>
                                </button>
                                {{ endbuttons }}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    {% endblock conteudo %}
</body>

</html>

contabilidade/templates/conta_nova.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

<body>
    {% block conteudo %}
    <main>
        <div class="container-fluid">
            <div id="conta-nova">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <h3 class="main-title">Nova Conta</h3>
                        </div>
                        <!-- Dividindo em duas colunas da mesma largura -->
                        <div class="col-md-6">
                            <img class="img-fluid" src="{% static 'img/agencia.jpg' %}" alt="Fachada de uma empresa">
                        </div>
                        <div class="col-md-6">
                            <h3 class="about-title">Uma nova conta financeira</h3>
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-content form-content-grid">
                                    {% for campos in form %}
                                    <div class="form-group">
                                        <label for="{{ campos.id_for_label }}">{{ campos.label }}</label>
                                        {{ campos }}

                                        {% if campos.help_text %}
                                        <p class="help_text">{{ campos.help_text }}</p>
                                        {% endif %}

                                        {{ campos.errors }}
                                    </div>
                                    {% endfor %}
                                    <div class="form-group">
                                        <button type="submit">Enviar</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    {% endblock conteudo %}
</body>

</html>

contabilidade/templates/contact.html
<div id="contact-area">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="main-title">Entre em contato conosco</h3>
      </div>
      <div class="col-md-4 contact-box">
        <i class="fas fa-phone"></i>
        <p><span class="contact-tile">Ligue para: </span>(41) 99999-9999</p>
        <p><span class="contact-tile">Horário: </span>das 8:00 às 17:00</p>
      </div>
      <div class="col-md-4 contact-box">
        <i class="fas fa-envelope"></i>
        <p><span class="contact-tile">Mande um e-mail: </span>fmorae05@outlook.com</p>
      </div>
      <div class="col-md-4 contact-box">
        <i class="fas fa-map-marker-alt"></i>
        <p><span class="contact-tile">Venha tomar um café: </span>Rua Eugênio da Silva Lopes, 441 - Alto Boqueirão - Curitiba/Pr</p>
      </div>
      <div class="col-md-6" id="msg-box">
        <p>Ou nos deixe uma mensagem...</p>
      </div>
      <div class="col-md-6" id="contact-form">
        <form action="">
          <input type="email" class="form-control" placeholder="Seu e-mail" name="email">
          <input type="text" class="form-control" placeholder="Assunto" name="subject">
          <textarea class="form-control" rows="3" placeholder="Sua mensagem..." name="message"></textarea>
          <input type="submit" class="main-btn" value="Enviar">
        </form>
      </div>
    </div>
  </div>
</div>

contabilidade/templates/family.html
{% load static %}
<!-- Página sobre a família -->
<div id="about-area">
    <div class="container">
        <!-- DIV com uma linha e doze colunas -->
        <div class="row">
            <div class="col-12">
                <h3 class="main-title">Sobre a família M&M</h3>
            </div>
            <!-- Colocando as colunas respeitando as medidas da tela -->
            <div class="col-md-6">
                <img src="{% static 'img/IMG-20191215-WA0001.jpg' %}" alt="Foto da família" class="img-fluid">
            </div>
            <div class="col-md-6">
                <h3 class="about-title">Família Moreira de Moraes</h3>
                <p>É uma família composta de 4 indivíduos muito fortes, prontos para qualquer eventualidade.</p>
                <p>Somos uma família muito unida e coesa, sempre pensando no futuro e guiados pelo Altíssimo.</p>
                <p>Estamos sempre dispostos a se ajudar em qualquer ocasião.</p>
                <p>Os membros da família são:</p>
                <ul id="about-list">
                    <li><i class="fa-solid fa-person-dress"></i>Rachel Moreira de Moraes</li>
                    <li><i class="fa-solid fa-person"></i>Fábio Rodrigues de Moraes</li>
                    <li><i class="fa-solid fa-person"></i>Victor Moreira de Moraes</li>
                    <li><i class="fa-solid fa-person-dress"></i>Mariana Moreira de Moraes</li>
                </ul>
            </div>
        </div>
    </div>
</div>

contabilidade/templates/financas.html
<!-- Dados financeiros(Parallax) -->
<div id="data-area">
  <div class="container">
    <div class="row">
      <div class="col-md-3 circle-box">
        <div id="circleA"></div>
        <p>Média de transações</p>
      </div>
      <div class="col-md-3 circle-box">
        <div id="circleB"></div>
        <p>Relatórios realizados</p>
      </div>
      <div class="col-md-3 circle-box">
        <div id="circleC"></div>
        <p>Consultas executadas</p>
      </div>
      <div class="col-md-3 circle-box">
        <div id="circleD"></div>
        <p>Média de pagamentos por mês</p>
      </div>
    </div>
  </div>
</div>

contabilidade/templates/history.html
<!-- Um pouco de história -->
<div id="history-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 history-box" id="company-img"></div>
            <div class="col-md-6 history-box" id="pattern-img">
                <h4>Algumas palavras</h4>
                <p>Nosso controle financeiro familiar começou quando fomos verificar nossa conta-corrente a vários anos atrás e</p>
                <p>descobrimos que se eu fosse desligado da empresa, na época trabalhava para o HSBC estaríamos completamente</p>
                <p>sem dinheiro e com muitas dívidas.</p>
                <p>Resolvemos então criar o primeiro controle financeiro para colocar as contas em dia...</p>
                <a href="#" class="main-btn" id="history-btn">Saiba mais</a>
            </div>
        </div>
    </div>
</div>

contabilidade/templates/homepage.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block conteudo %}
<main>
    <div class="container-fluid">
        <div id="mainSlider" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#mainSlider" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#mainSlider" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#mainSlider" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active" data-bs-interval="120000">
                    <img src="{% static 'img/banner1.png' %}" class="d-block w-100"
                        alt="Lista de Contas Financeiras disponíveis">
                    <div class="carousel-caption d-none-d-md-block">
                        <h2>Próximos pagamentos/recebimentos</h2>
                        <p>Aqui aparecem os próximos pagamentos e recebimentos financeiros.</p>
                        <a href="#" class="main-btn">Nova transação</a>
                    </div>
                </div>
                <div class="carousel-item" data-bs-interval="60000">
                    <img src="{% static 'img/banner2.png' %}" class="d-block w-100"
                        alt="Lista de Contas Financeiras disponíveis">
                    <div class="carousel-caption d-none-d-md-block">
                        <h2>Contas Financeiras disponíveis</h2>
                        <table class="table table-hover table-sm">
                            <thead class="table-dark">
                                <tr>
                                    <th scope="col">Conta</th>
                                    <th scope="col">Saldo</th>
                                    <th scope="col">Data Criação</th>
                                    <th scope="col">Última Atualização</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Ação</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for reg in contas %}
                                <tr>
                                    <td>{{reg.nome}}</td>
                                    <td>R$ {{reg.saldo|intcomma}}</td>
                                    <td>{{reg.criado}}</td>
                                    <td>{{reg.modificado}}</td>
                                    {% if reg.ativo == True %}
                                    <td>Ativa</td>
                                    {% else %}
                                    <td>Inativa</td>
                                    {% endif %}
                                    <td>
                                        <a class="btn btn-warning btn-sm" href="{% url 'contabilidade:alterar_conta' reg.pk %}">Editar</a>
                                        <a class="btn btn-danger  btn-sm" href="{% url 'contabilidade:excluir_conta' reg.pk %}">Excluir</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <a href="{% url 'contabilidade:nova_conta' %}" class="main-btn">Nova Conta</a>
                    </div>
                </div>
                <div class="carousel-item" data-bs-interval="30000">
                    <img src="{% static 'img/banner3.png' %}" class="d-block w-100"
                        alt="Lista de Contas Financeiras disponíveis">
                    <div class="carousel-caption d-none-d-md-block">
                        <h2>Contabilidade da Família M&M</h2>
                        <p>Este site fará o gerenciamento financeiro da família.</p>
                        <a href="#" class="main-btn">Mais informações</a>
                    </div>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#mainSlider" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#mainSlider" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
    {% include 'family.html' %}
    {% include 'services.html' %}
    {% include 'financas.html' %}
    {% include 'team.html' %}
    {% include 'history.html' %}
    {% include 'portfolio.html' %}
    {% include 'newsletter.html' %}
    {% include 'contact.html' %}
</main>
<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
{% endblock %}

contabilidade/templates/newsletter.html
<!-- Newsletter -->
<div id="news-area">
    <div class="container">
        <div class="col-md-12">
            <h3 class="main-title">Fique por dentro das novidades</h3>
        </div>
        <p>Assine nossa lista de e-mails e acompanhe o andamento dos projetos.</p>
        <form action="">
            <input type="email" class="form-control" name="email" id="email-input" placeholder="Seu melhor e-mail">
            <input type="submit" id="news-btn" value="Enviar">
        </form>
    </div>
</div>
<!-- Call to action -->
<div id="call-area">
    <div class="container">
        <div class="row">
            <p>Deseja enviar um recado?</p>
            <button class="main-btn" id="call-btn">Recado</button>
        </div>
    </div>
</div>

contabilidade/templates/partials/footer.html
<footer>
    <div id="copy-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p>Desenvolvido por <a href="https://github.com/Fabio-R-Moraes" target="_blank">Fábio Rodrigues de
                            Moraes</a> &copy; 2024</p>
                </div>
            </div>
        </div>
    </div>
</footer>

contabilidade/templates/partials/head.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Fonte do Google -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rakkas&display=swap" rel="stylesheet">

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Estilos -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <!-- Fonte Awesome -->
    <script src="https://kit.fontawesome.com/693e59b542.js" crossorigin="anonymous"></script>

    <!-- Progressbar -->
    <script type="text/javascript" src="{% static 'js/progressbar.min.js' %}"></script>

    <!-- parallax -->
    <script src="https://cdn.jsdelivr.net/parallax.js/1.4.2/parallax.min.js"></script>

    <title>Família M&M</title>
</head>

contabilidade/templates/partials/header.html
{% load static %}
<header>
    <div class="container" id="nav-container">
        <nav class="navbar navbar-expand-lg fixed-top">
            <a href="{% url 'contabilidade:homepage' %}" class="navbar-brand">
                <img id="logo" src="{% static 'img/saco_dinheiro.svg' %}" alt="Saco de Dinheiro"> Família M&M
            </a>

            <!-- Botão hamburguer para aparecer no celular -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-links"
                aria-controls="navbar-links" aria-expanded="false" aria-label="toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Barra de navegação -->
            <div class="collapse navbar-collapse justify-content-end" id="navbar-links">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" id="home-menu" href="{% url 'contabilidade:homepage' %}">Home</a>
                    <a class="nav-item nav-link" id="about-menu">Família</a>
                    <a class="nav-item nav-link" id="services-menu">Serviços</a>
                    <a class="nav-item nav-link" id="team-menu">Equipe</a>
                    <a class="nav-item nav-link" id="portfolio-menu">Projetos</a>
                    <a class="nav-item nav-link" id="contact-menu">Contato</a>
                </div>
            </div>
        </nav>
    </div>
</header>

contabilidade/templates/portfolio.html
{% load static %}
<!-- Portfólio -->
<div id="portfolio-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 class="main-title">Conheça nossos projetos</h3>
            </div>
            <div class="col-md-12" id="filter-btn-box">
                <button class="main-btn filter-btn active" id="all-btn">Todos</button>
                <button class="main-btn filter-btn" id="fin-btn">Financeiro</button>
                <button class="main-btn filter-btn" id="lot-btn">Loterias</button>
                <button class="main-btn filter-btn" id="esp-btn">Esportes</button>
            </div>
            <div class="col-md-4 portfolio-box fin">
                <img src="{% static 'img/proj_financeiro.jpg' %}" alt="Projeto Financeiro" class="img-fluid">
            </div>
            <div class="col-md-4 portfolio-box esp">
                <img src="{% static 'img/proj_futebol.jpg' %}" alt="Projeto Futebol" class="img-fluid">
            </div>
            <div class="col-md-4 portfolio-box lot">
                <img src="{% static 'img/proj_lotofacil.jpg' %}" alt="Projeto LotoFacil" class="img-fluid">
            </div>
            <div class="col-md-4 portfolio-box lot">
                <img src="{% static 'img/proj_lotomania.jpg' %}" alt="Projeto LotoMania" class="img-fluid">
            </div>
            <div class="col-md-4 portfolio-box lot">
                <img src="{% static 'img/proj_megasena.jpg' %}" alt="Projeto MegaSena" class="img-fluid">
            </div>
            <div class="col-md-4 portfolio-box lot">
                <img src="{% static 'img/proj_timemania.jpg' %}" alt="Projeto TimeMania" class="img-fluid">
            </div>
        </div>
    </div>
</div>

contabilidade/templates/services.html
<!-- Serviços realizados pelo sistema financeiro -->
<div id="services-area">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h3 class="main-title">Serviços Financeiros</h3>
      </div>
      <div class="col-md-4 service-box">
        <i class="fas fa-mobile-alt"></i>
        <h4>Telefone celular</h4>
        <p>O sistema pode ser utilizado em telefones celulares.</p>
      </div>
      <div class="col-md-4 service-box">
        <i class="fa-brands fa-readme"></i>
        <h4>Relatórios</h4>
        <p>Podem ser retirados relatórios de diversos tipos no sistema.</p>
      </div>
      <div class="col-md-4 service-box">
        <i class="fa-solid fa-marker"></i>
        <h4>Transações financeiras</h4>
        <p>Guarde todas as suas transações financeiras no sistema, ele está preparado para isso.</p>
      </div>
      <div class="col-md-4 service-box">
        <i class="fa-solid fa-cash-register"></i>
        <h4>Sumários por conta</h4>
        <p>Sumários mensais e anuais por qualquer conta que seja consultada.</p>
      </div>
      <div class="col-md-4 service-box">
        <i class="fa-solid fa-wallet"></i>
        <h4>Financiamento</h4>
        <p>Controle completamente os financiamentos feitos para poder tomar decisões futuras.</p>
      </div>
      <div class="col-md-4 service-box">
        <i class="fa-solid fa-mountain-sun"></i>
        <h4>Planejamento</h4>
        <p>Facilite seus planejamentos financeiros...</p>
      </div>
    </div>
  </div>
</div>

contabilidade/templates/team.html
{% load static %}
<!-- Membros da família -->
<div id="team-area">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h3 class="main-title">Membros da família</h3>
      </div>
      <div class="col-md-3">
        <div class="card">
          <img src="{% static 'img/Fabio.png' %}" class="card-img-top" alt="Pai da família">
          <div class="card-body">
            <h5 class="card-title">Fábio Rodrigues de Moraes</h5>
            <p class="card-text">Pai e provedor</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card">
          <img src="{% static 'img/Rachel.png' %}" class="card-img-top" alt="Mãe da família">
          <div class="card-body">
            <h5 class="card-title">Rachel Moreira de Moraes</h5>
            <p class="card-text">Mãe e porto seguro</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card">
          <img src="{% static 'img/Victor.png' %}" class="card-img-top" alt="Filho">
          <div class="card-body">
            <h5 class="card-title">Victor Moreira de Moraes</h5>
            <p class="card-text">Filho e desenvolvedor</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card">
          <img src="{% static 'img/Mariana.png' %}" class="card-img-top" alt="Filha">
          <div class="card-body">
            <h5 class="card-title">Mariana Moreira de Moraes</h5>
            <p class="card-text">Filha e artista</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>